services:
  linguist:
    image: ghcr.io/github-linguist/linguist:v9.5.0@sha256:24d32762687af71000f2a7ccbd3eb567519b022025578b339d33c97982d82ec6
    working_dir: /src
    user: "${USER_ID}:${GROUP_ID}"
    environment:
      - GIT_CONFIG_GLOBAL=/tmp/.gitconfig
    volumes:
      - .:/src:ro,z
