---
name: Supply Chain Security Validation
on:
  workflow_call:
    inputs:
      codeql-code-scanning-category:
        default: codeql-code-scanning
        type: string
        required: false
      tfsec-code-scanning-category:
        default: tfsec-code-scanning
        type: string
        required: false
    secrets: {}
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs:
      - dependency-review
      - code-scanning
      - tfsec
    steps:
      - run: "echo SUCCESS"

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v1

  code-scanning:
    name: CodeQL Scanning
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/github-script@v2
        name: Get CodeQL supported languages
        id: languages
        with:
          result-encoding: json
          script: |
            const result = await github.repos.listLanguages({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const codeqlLanguages = ['cpp', 'csharp', 'go', 'ruby', 'python', 'java', 'javascript', 'typescript'];
            const languages = Object.keys(result['data']).filter(language => codeqlLanguages.includes(language.toLowerCase()));
            return languages;
      - name: Check out repository
        if: steps.languages.outputs.result != '[]'
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        if: steps.languages.outputs.result != '[]'
        uses: github/codeql-action/init@v2
      - name: Autobuild
        if: steps.languages.outputs.result != '[]'
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        if: steps.languages.outputs.result != '[]'
        uses: github/codeql-action/analyze@v2
        with:
          category: ${{ inputs.codeql-code-scanning-category }}

  tfsec:
    name: tfsec Scanning
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Terrform files Count
        id: terraform_files
        run: echo "::set-output name=count::$(find . -name '*.tf' | wc -l | xargs)"
      - name: tfsec
        if: steps.terraform_files.outputs.count != '0'
        uses: aquasecurity/tfsec-sarif-action@v0.1.3
        with:
          sarif_file: tfsec.sarif
      - name: Upload SARIF file
        if: steps.terraform_files.outputs.count != '0'
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: ${{ inputs.tfsec-code-scanning-category }}
          sarif_file: tfsec.sarif
