name: Supply Chain
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_call:
    inputs:
      run-code-scanning:
        default: true
        type: boolean
        required: false
      codeql-code-scanning-category:
        default: codeql-code-scanning
        type: string
        required: false
      codeql-code-scanning-config-file:
        default:
        type: string
        required: false
      codeql-go-version:
        type: string
        required: false
      codeql-java-version:
        default: 17
        type: string
        required: false
      codeql-java-cache:
        default:
        type: string
        required: false
      codeql-java-distribution:
        default: adopt
        type: string
        required: false
      code-scanning-timeout-minutes:
        default: 10
        type: number
        required: false
      trivy-code-scanning-category:
        default: trivy-code-scanning
        type: string
        required: false
    secrets: {}
jobs:
  validate:
    name: Validate
    if: always()
    runs-on: ubuntu-24.04
    needs:
      - dependency-review
      - code-scanning
      - trivy
    steps:
      - run: exit 1
        name: "Catch errors"
        if: ${{ contains(join(needs.*.result, ','), 'failure') || contains(join(needs.*.result, ','), 'cancelled') }}

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-24.04

    if: github.event_name == 'pull_request'
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Dependency Review
        uses: actions/dependency-review-action@v4

  code-scanning:
    name: CodeQL Scan
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.code-scanning-timeout-minutes }}
    if: ${{ inputs.run-code-scanning == true && github.event_name != 'pull_request' }}
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Configure access to internal and private GitHub repos
        run: git config --global url."https://${{ secrets.REVIEWBOT_GITHUB_TOKEN }}:x-oauth-basic@github.com/coopnorge".insteadOf "https://github.com/coopnorge"
      - uses: fabasoad/setup-enry-action@e81ba89a68c7823cea7b3bf591999534f7236441 # pin@main
      - name: Detected Languages
        id: detected-languages
        run: echo "languages=$(enry | awk -F ' ' '{print $2}' | paste -sd ',' -)" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v8
        name: Get CodeQL supported languages
        id: languages
        with:
          result-encoding: json
          script: |
            const enryCodeQLMapping = {
              'c#': 'csharp',
            };
            function getCodeQLLanguage(enryLang) {
              if (enryLang in enryCodeQLMapping) {
                return enryCodeQLMapping[enryLang];
              }
              return enryLang;
            }
            const detectedLanguages = '${{ steps.detected-languages.outputs.languages }}'.toLowerCase().split(',').map(language => {
              return getCodeQLLanguage(language)
            });

            // Always scan for actions
            // Enry does not find GitHub actions and they always exist if this workflow is running
            // So, always add it.
            detectedLanguages.push('actions');

            const codeqlLanguages = ['c', 'cpp', 'csharp', 'go', 'python', 'java', 'javascript', 'typescript', 'actions'];
            const languages = detectedLanguages.filter(language => codeqlLanguages.includes(language));
            return languages.join(',');
      
      - name: "Determine Go version"
        run: |
          if [ -z "${{ inputs.codeql-go-version }}" ]; then
            echo "GO_VERSION=stable" >> $GITHUB_ENV
            echo "GO_CHECK_LATEST=true" >> $GITHUB_ENV
          else
            echo "GO_VERSION=${{ inputs.codeql-go-version }}" >> $GITHUB_ENV
            echo "GO_CHECK_LATEST=false" >> $GITHUB_ENV
          fi
      - name: Set Go version
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: ${{ env.GO_CHECK_LATEST }}
          cache: true
          cache-dependency-path: "**/go.sum"
      
      - name: Set Java version
        uses: actions/setup-java@v5
        with:
          distribution: ${{ inputs.codeql-java-distribution }}
          java-version: ${{ inputs.codeql-java-version }}
          cache: ${{ inputs.codeql-java-cache }}
      - name: Setup Maven settings
        if: ${{ env.MAVEN_SETTINGS != '' }}
        env: 
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS_BASE64 }}
        run: |
          mkdir -p ~/.m2
          echo $MAVEN_SETTINGS | base64 -d > ~/.m2/settings.xml
            
      - name: Initialize CodeQL
        if: steps.languages.outputs.result != '""'
        uses: github/codeql-action/init@v3
        with:
          config-file: ${{ inputs.codeql-code-scanning-config-file }}
          languages: ${{ fromJSON(steps.languages.outputs.result) }}
      - name: Add coopnorge Nuget source
        if: contains(steps.languages.outputs.result, 'csharp')
        run: |
          dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/coopnorge/index.json"
      - name: Autobuild
        if: steps.languages.outputs.result != '""'
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        if: steps.languages.outputs.result != '""'
        uses: github/codeql-action/analyze@v3
        with:
          category: ${{ inputs.codeql-code-scanning-category }}

  trivy:
    name: trivy Scan
    runs-on: ubuntu-24.04
    if: github.event_name != 'pull_request'
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: trivy
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # pin@0.33.1
        with:
          scan-type: fs
          format: sarif
          scanners: vuln,secret
          vuln-type: os
          output: trivy-results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: ${{ inputs.trivy-code-scanning-category }}
          sarif_file: trivy-results.sarif
